name: fmq
baseurl: /fmq
description: Functional ZeroMQ library
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.1+1-926cd06e-SNAPSHOT
org: io.github.irevive
markdown: kramdown
