name: fmq
baseurl: /fmq
description: Functional ZeroMQ library
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.2.1+1-762b5463-SNAPSHOT
org: io.github.irevive
markdown: kramdown
