name: fmq
baseurl: /fmq
description: fMQ - Functional ZeroMQ library
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.1-SNAPSHOT
org: io.github.irevive
markdown: kramdown
