addSbtPlugin("org.scoverage"             % "sbt-scoverage"   % "1.8.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"    % "2.4.2")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"        % "2.2.20")
addSbtPlugin("org.wartremover"           % "sbt-wartremover" % "2.4.15")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"    % "0.1.17")
addSbtPlugin("com.geirsson"              % "sbt-ci-release"  % "1.5.7")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"         % "0.4.2")
