addSbtPlugin("org.scoverage"             % "sbt-scoverage"   % "1.6.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"    % "2.3.2")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"        % "2.1.5")
addSbtPlugin("org.wartremover"           % "sbt-wartremover" % "2.4.5")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"    % "0.1.11")
addSbtPlugin("com.47deg"                 % "sbt-microsites"  % "1.1.4")
addSbtPlugin("com.geirsson"              % "sbt-ci-release"  % "1.5.2")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"         % "0.3.7")
