name: Release
on:
  push:
    branches:
      - release
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: olafurpg/setup-scala@v13
      - uses: olafurpg/setup-gpg@v3
      - name: Publish
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      - name: Publish docs
        run: sbt ++2.13.7 docs/docusaurusPublishGhpages
        env:
          GIT_DEPLOY_KEY: ${{ secrets.GITHUB_DEPLOY_KEY }}
