name: Website manual
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
      - uses: olafurpg/setup-gpg@v3
      - run: sbt '++2.13.7 docs/docusaurusPublishGhpages'
        env:
          GIT_DEPLOY_KEY: ${{ secrets.GITHUB_DEPLOY_KEY }}
          RELEASE_VERSION: ${{ github.event.inputs.version }}
      - name: Check git diff
        if: ${{ failure() }}
        run: git diff
